# Generated by Django 5.0.6 on 2024-05-27 06:56

import django.db.models.deletion
import encrypted_model_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Range',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Range', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Parameters', encrypted_model_fields.fields.EncryptedCharField(default='')),
                ('date_added', models.DateField(auto_now_add=True)),
                ('Range', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cabin.range')),
            ],
        ),
    ]
